### ISSUE TITLE
[FEATURE]: add default value in the space class and use it in get()

### ISSUE THREAD

**Issue by joticajulian** [koinos/koinos-sdk-as#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

Right now the way to get a value using the space class is this one
```
    this.balances = new Space.Space(
      this.contractId,
      BALANCES_SPACE_ID,
      token.uint64.decode,
      token.uint64.encode
    );

    let fromBalance = this.balances.get(from);
    if (!fromBalance) fromBalance = new token.uint64(0);
```

Since the `get()` function can return `null`, it is always necessary to set a default value after it is done.

The proposal here is to pass a default value in the constructor of the Space class. If it is defined then it will be returned in `get()` when there is no data in the database, otherwise it returns null as before.

So the dev can do something like this:
```
    this.balances = new Space.Space(
      this.contractId,
      BALANCES_SPACE_ID,
      new token.uint64(0), // this is the default value
      token.uint64.decode,
      token.uint64.encode
    );

    const fromBalance = this.balances.get(from);
    // the type still includes "null"
    // however, as developer knows that it is defined
    // he could just use fromBalance!
    
    if (fromBalance!.value < value) {
      ...
    }
```

**Comment by sgerbino** [comment]
Resolved by #54.
