### ISSUE TITLE
[FEATURE]: Space class used to store single values

### ISSUE THREAD

**Issue by joticajulian** [koinos/koinos-sdk-as#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

The Space class is useful to not only to store a set of values (like balances) but also to store a single value. Here is an example for "totalSupply".

```
    this.supply = new Space.Space(
      this.contractId,
      SUPPLY_ID,
      token.uint64.decode,
      token.uint64.encode
    );

    const defaultKey = new Uint8Array(0);

    // get total supply
    let supply = this.supply.get(defaultKey);

    // save total supply
    this.supply.put(defaultKey, newSupply);
```

The advantage of this pattern design is that the `decoder` and `encoder` are defined in the constructor of the space class and there is no need to call them again in the code, making the code more readable.

However, it still needs the definition of a `defaultKey`, which must be called on each `get` and `put`. And this can be confusing for the developers.

The proposal here is to extend the Space class for single values, that is, include the `defaultKey` inside the class. The functions to put and get could work in this way:

```
// space with a set of values
this.balances.put(newBalance, owner);
this.balances.get(owner);

// space with a single value
this.totalSupply.put(newSupply);
this.totalSupply.get();
```

**Comment by sgerbino** [comment]
Resolved by #54.
