### ISSUE TITLE
[FEATURE]: improve error messages in token.ts

### ISSUE THREAD

**Issue by joticajulian** [koinos/koinos-sdk-as#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

In `token.ts`, if some function fails after making the `system.call`, the function returns false but the error message is not handled. Then this information is lost.

One example is the koin contract called inside the PoB contract: If the user burns koins to get vhp but there is no enough mana, the error message is just "could not burn koin".

We could call `System.log` in such cases and put the error message there. In this sense the user could get more information from the logs to understand what happened.

**Comment by mvandeberg** [comment]
Error messages were properly handled in system call implementations, but not in token.ts
